name: Release

on:
  push:
    tags:
      - 'v*'   # trigger on tags like v0.9.1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller packaging requests pywin32

      # Optional: list files for quick debugging
      - name: List repo files (debug)
        shell: pwsh
        run: |
          Get-ChildItem -Force | Select-Object Name,Length,LastWriteTime | Format-Table

      # Build EXE (note: main file is NFtool.py with lowercase "t")
      - name: Build EXE
        shell: cmd
        run: |
          pyinstaller --onefile --windowed --noconfirm --name NFTOOL --icon=Ficon_multi.ico ^
            --add-data "play_darkmode_smooth.png;." ^
            --add-data "pause_darkmode_smooth.png;." ^
            --add-data "trash_dark_smooth.png;." ^
            --add-data "add_darkmode_smooth.png;." ^
            --add-data "Ficon_multi.ico;." NFtool.py

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path dist/NFTOOL.exe -DestinationPath NFTOOL.zip -Force

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/NFTOOL.exe
            NFTOOL.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
